# Generated by Django 2.2.4 on 2019-08-27 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Message_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Matches',
            new_name='Message',
        ),
    ]
