# Generated by Django 2.2.4 on 2019-08-27 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Message_app', '0002_auto_20190827_1833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message',
            new_name='content',
        ),
    ]
